### ISSUE TITLE
Additional Instructions

### ISSUE THREAD

**Issue by reteps** [chinrw/wsl-qemu-kvm#1]
I had to perform additional steps to get this working in WSL2:

```
sudo usermod -a -G kvm ${USER}
```

and then either run
```
/bin/bash -c 'chown -v root:kvm /dev/kvm && chmod 660 /dev/kvm'
```

or add to your `wsl.conf`:
```
command = /bin/bash -c 'chown -v root:kvm /dev/kvm && chmod 660 /dev/kvm'
```

I had to install `attr` package too.

[source](https://serverfault.com/questions/1043441/how-to-run-kvm-nested-in-wsl2-or-vmware)

**Comment by chinrw** [comment]
Thanks, will update this.
